packages:
    - 'chocolatey'
    - 'googlechrome'
    - 'firefox'
    - 'azure-cli'
    - 'awscli'
    - 'cmder'
    - 'postman'
    - 'nuget.commandline'
    - 'git'
    - 'git-credential-manager-for-windows'
    - 'pester'
    - 'Plaster'
    - 'dbatools'
    - 'psake'
    - 'oh-my-posh'
    - 'pwsh'
    - 'vscode'
    - 'notepad2'
    - 'vim'
    - 'sharpkeys'
    - 'microsoft-teams'